version: '3.9'

services:
  web:
    image: frontend    
    ports:
      - "3000:3000"
    
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shoppingCartService
      MySQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3309:3306"

  testdb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shoppingCartService
      MySQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3310:3306"


  backend:
    image: backend
    ports:
      - "8080:8080"
    command: 
    - "sleep"
    - "infinity"
  